<option value="{{ __('cities.Aqiq')}}">{{ __('cities.Aqiq')}}</option>
<option value="{{ __('cities.Atawlah')}}">{{ __('cities.Atawlah')}}</option>
<option value="{{ __('cities.Baha')}}">{{ __('cities.Baha')}}</option>
<option value="{{ __('cities.Baljurashi')}}">{{ __('cities.Baljurashi')}}</option>
<option value="{{ __('cities.Mandaq')}}">{{ __('cities.Mandaq')}}</option>
<option value="{{ __('cities.Mudhaylif')}}">{{ __('cities.Mudhaylif')}}</option>
<option value="{{ __('cities.Mukhwah')}}">{{ __('cities.Mukhwah')}}</option>
<option value="{{ __('cities.Qilwah')}}">{{ __('cities.Qilwah')}}</option>
<option value="{{ __('cities.Qunfudhah')}}">{{ __('cities.Qunfudhah')}}</option>
<option value="{{ __('cities.Al Jouf')}}">{{ __('cities.Al Jouf')}}</option>
<option value="{{ __('cities.Dawmat Al Jandal')}}">{{ __('cities.Dawmat Al Jandal')}}</option>
<option value="{{ __('cities.Skakah')}}">{{ __('cities.Skakah')}}</option>
<option value="{{ __('cities.Bashayer')}}">{{ __('cities.Bashayer')}}</option>
<option value="{{ __('cities.Bellasmar')}}">{{ __('cities.Bellasmar')}}</option>
<option value="{{ __('cities.Namas')}}">{{ __('cities.Namas')}}</option>
<option value="{{ __('cities.Sapt Al Alaya')}}">{{ __('cities.Sapt Al Alaya')}}</option>
<option value="{{ __('cities.Tanumah')}}">{{ __('cities.Tanumah')}}</option>
<option value="{{ __('cities.Ain Dar')}}">{{ __('cities.Ain Dar')}}</option>
<option value="{{ __('cities.Anak')}}">{{ __('cities.Anak')}}</option>
<option value="{{ __('cities.Bahrain Causeway')}}">{{ __('cities.Bahrain Causeway')}}</option>
<option value="{{ __('cities.Buqaiq')}}">{{ __('cities.Buqaiq')}}</option>
<option value="{{ __('cities.Dammam')}}">{{ __('cities.Dammam')}}</option>
<option value="{{ __('cities.Dammam Airport')}}">{{ __('cities.Dammam Airport')}}</option>
<option value="{{ __('cities.Dhahran')}}">{{ __('cities.Dhahran')}}</option>
<option value="{{ __('cities.Jubail')}}">{{ __('cities.Jubail')}}</option>
<option value="{{ __('cities.Khafji')}}">{{ __('cities.Khafji')}}</option>
<option value="{{ __('cities.Khubar')}}">{{ __('cities.Khubar')}}</option>
<option value="{{ __('cities.Muneefa')}}">{{ __('cities.Muneefa')}}</option>
<option value="{{ __('cities.Qarya Al Uliya')}}">{{ __('cities.Qarya Al Uliya')}}</option>
<option value="{{ __('cities.Qatif')}}">{{ __('cities.Qatif')}}</option>
<option value="{{ __('cities.Rahima')}}">{{ __('cities.Rahima')}}</option>
<option value="{{ __('cities.Ras Tannurah')}}">{{ __('cities.Ras Tannurah')}}</option>
<option value="{{ __('cities.Safwa')}}">{{ __('cities.Safwa')}}</option>
<option value="{{ __('cities.Saira')}}">{{ __('cities.Saira')}}</option>
<option value="{{ __('cities.Sayhat')}}">{{ __('cities.Sayhat')}}</option>
<option value="{{ __('cities.Shedgum')}}">{{ __('cities.Shedgum')}}</option>
<option value="{{ __('cities.Tanajib')}}">{{ __('cities.Tanajib')}}</option>
<option value="{{ __('cities.Tarut (Darin)')}}">{{ __('cities.Tarut (Darin)')}}</option>
<option value="{{ __('cities.Thqbah')}}">{{ __('cities.Thqbah')}}</option>
<option value="{{ __('cities.Udhayliyah')}}">{{ __('cities.Udhayliyah')}}</option>
<option value="{{ __('cities.Uthmaniyah')}}">{{ __('cities.Uthmaniyah')}}</option>
<option value="{{ __('cities.Najran')}}">{{ __('cities.Najran')}}</option>
<option value="{{ __('cities.Sharourah')}}">{{ __('cities.Sharourah')}}</option>
<option value="{{ __('cities.Wadi Al-Dawasir')}}">{{ __('cities.Wadi Al-Dawasir')}}</option>
<option value="{{ __('cities.Badaya')}}">{{ __('cities.Badaya')}}</option>
<option value="{{ __('cities.Bukayriyah')}}">{{ __('cities.Bukayriyah')}}</option>
<option value="{{ __('cities.Buraydah')}}">{{ __('cities.Buraydah')}}</option>
<option value="{{ __('cities.Dukhnah')}}">{{ __('cities.Dukhnah')}}</option>
<option value="{{ __('cities.Khabra')}}">{{ __('cities.Khabra')}}</option>
<option value="{{ __('cities.Midhnab')}}">{{ __('cities.Midhnab')}}</option>
<option value="{{ __('cities.Nabaniya')}}">{{ __('cities.Nabaniya')}}</option>
<option value="{{ __('cities.Nabhaniah')}}">{{ __('cities.Nabhaniah')}}</option>
<option value="{{ __('cities.Nifi')}}">{{ __('cities.Nifi')}}</option>
<option value="{{ __('cities.Qaseem Airport')}}">{{ __('cities.Qaseem Airport')}}</option>
<option value="{{ __('cities.Rafayaa Al Gimsh')}}">{{ __('cities.Rafayaa Al Gimsh')}}</option>
<option value="{{ __('cities.Rass')}}">{{ __('cities.Rass')}}</option>
<option value="{{ __('cities.Riyadh Al Khabra')}}">{{ __('cities.Riyadh Al Khabra')}}</option>
<option value="{{ __('cities.Sajir')}}">{{ __('cities.Sajir')}}</option>
<option value="{{ __('cities.Unayzah')}}">{{ __('cities.Unayzah')}}</option>
<option value="{{ __('cities.Uqlat As Suqur')}}">{{ __('cities.Uqlat As Suqur')}}</option>
<option value="{{ __('cities.Uyun Al Jiwa')}}">{{ __('cities.Uyun Al Jiwa')}}</option>
<option value="{{ __('cities.Abu Arish')}}">{{ __('cities.Abu Arish')}}</option>
<option value="{{ __('cities.Ahad Al Masarhah')}}">{{ __('cities.Ahad Al Masarhah')}}</option>
<option value="{{ __('cities.Al Dayer')}}">{{ __('cities.Al Dayer')}}</option>
<option value="{{ __('cities.Bani Malek')}}">{{ __('cities.Bani Malek')}}</option>
<option value="{{ __('cities.Baysh')}}">{{ __('cities.Baysh')}}</option>
<option value="{{ __('cities.Darb')}}">{{ __('cities.Darb')}}</option>
<option value="{{ __('cities.Dhamad')}}">{{ __('cities.Dhamad')}}</option>
<option value="{{ __('cities.Farasan')}}">{{ __('cities.Farasan')}}</option>
<option value="{{ __('cities.Jazan')}}">{{ __('cities.Jazan')}}</option>
<option value="{{ __('cities.Sabya')}}">{{ __('cities.Sabya')}}</option>
<option value="{{ __('cities.Samtah')}}">{{ __('cities.Samtah')}}</option>
<option value="{{ __('cities.Hail')}}">{{ __('cities.Hail')}}</option>
<option value="{{ __('cities.Sayirah')}}">{{ __('cities.Sayirah')}}</option>
<option value="{{ __('cities.Al Ruqi')}}">{{ __('cities.Al Ruqi')}}</option>
<option value="{{ __('cities.Hafar Al Baten')}}">{{ __('cities.Hafar Al Baten')}}</option>
<option value="{{ __('cities.King Khalid City')}}">{{ __('cities.King Khalid City')}}</option>
<option value="{{ __('cities.Qaysumah')}}">{{ __('cities.Qaysumah')}}</option>
<option value="{{ __('cities.Rafha')}}">{{ __('cities.Rafha')}}</option>
<option value="{{ __('cities.Sarrar')}}">{{ __('cities.Sarrar')}}</option>
<option value="{{ __('cities.Al Ahsa')}}">{{ __('cities.Al Ahsa')}}</option>
<option value="{{ __('cities.Al Ayun')}}">{{ __('cities.Al Ayun')}}</option>
<option value="{{ __('cities.Al Jafr')}}">{{ __('cities.Al Jafr')}}</option>
<option value="{{ __('cities.Batha')}}">{{ __('cities.Batha')}}</option>
<option value="{{ __('cities.Hufuf')}}">{{ __('cities.Hufuf')}}</option>
<option value="{{ __('cities.Mubarraz')}}">{{ __('cities.Mubarraz')}}</option>
<option value="{{ __('cities.Salwa')}}">{{ __('cities.Salwa')}}</option>
<option value="{{ __('cities.Badr')}}">{{ __('cities.Badr')}}</option>
<option value="{{ __('cities.Bahrah')}}">{{ __('cities.Bahrah')}}</option>
<option value="{{ __('cities.Jeddah')}}">{{ __('cities.Jeddah')}}</option>
<option value="{{ __('cities.Jeddah Airport')}}">{{ __('cities.Jeddah Airport')}}</option>
<option value="{{ __('cities.Kamil')}}">{{ __('cities.Kamil')}}</option>
<option value="{{ __('cities.Khulais')}}">{{ __('cities.Khulais')}}</option>
<option value="{{ __('cities.Lith')}}">{{ __('cities.Lith')}}</option>
<option value="{{ __('cities.Masturah')}}">{{ __('cities.Masturah')}}</option>
<option value="{{ __('cities.Rabigh')}}">{{ __('cities.Rabigh')}}</option>
<option value="{{ __('cities.Shaibah')}}">{{ __('cities.Shaibah')}}</option>
<option value="{{ __('cities.Thuwal')}}">{{ __('cities.Thuwal')}}</option>
<option value="{{ __('cities.Abha')}}">{{ __('cities.Abha')}}</option>
<option value="{{ __('cities.Ahad Rafidah')}}">{{ __('cities.Ahad Rafidah')}}</option>
<option value="{{ __('cities.Bariq')}}">{{ __('cities.Bariq')}}</option>
<option value="{{ __('cities.Bishah')}}">{{ __('cities.Bishah')}}</option>
<option value="{{ __('cities.Jash')}}">{{ __('cities.Jash')}}</option>
<option value="{{ __('cities.Khamis Mushayt')}}">{{ __('cities.Khamis Mushayt')}}</option>
<option value="{{ __('cities.Majardah')}}">{{ __('cities.Majardah')}}</option>
<option value="{{ __('cities.Muhayil')}}">{{ __('cities.Muhayil')}}</option>
<option value="{{ __('cities.Nakeea')}}">{{ __('cities.Nakeea')}}</option>
<option value="{{ __('cities.Rijal Almaa')}}">{{ __('cities.Rijal Almaa')}}</option>
<option value="{{ __('cities.Sarat Abida')}}">{{ __('cities.Sarat Abida')}}</option>
<option value="{{ __('cities.Tarib')}}">{{ __('cities.Tarib')}}</option>
<option value="{{ __('cities.Tathlith')}}">{{ __('cities.Tathlith')}}</option>
<option value="{{ __('cities.Wadi Bin Hashbal')}}">{{ __('cities.Wadi Bin Hashbal')}}</option>
<option value="{{ __('cities.Jamoum')}}">{{ __('cities.Jamoum')}}</option>
<option value="{{ __('cities.Makkah')}}">{{ __('cities.Makkah')}}</option>
<option value="{{ __('cities.Hanakiyah')}}">{{ __('cities.Hanakiyah')}}</option>
<option value="{{ __('cities.Khayber')}}">{{ __('cities.Khayber')}}</option>
<option value="{{ __('cities.Madinah')}}">{{ __('cities.Madinah')}}</option>
<option value="{{ __('cities.Mahd Ad Dhahab')}}">{{ __('cities.Mahd Ad Dhahab')}}</option>
<option value="{{ __('cities.Ula')}}">{{ __('cities.Ula')}}</option>
<option value="{{ __('cities.Afif')}}">{{ __('cities.Afif')}}</option>
<option value="{{ __('cities.Artawiyah')}}">{{ __('cities.Artawiyah')}}</option>
<option value="{{ __('cities.Bijadiyah')}}">{{ __('cities.Bijadiyah')}}</option>
<option value="{{ __('cities.Duwadimi')}}">{{ __('cities.Duwadimi')}}</option>
<option value="{{ __('cities.Ghat')}}">{{ __('cities.Ghat')}}</option>
<option value="{{ __('cities.Hawtat Sudayr')}}">{{ __('cities.Hawtat Sudayr')}}</option>
<option value="{{ __('cities.Majmaah')}}">{{ __('cities.Majmaah')}}</option>
<option value="{{ __('cities.Shaqra')}}">{{ __('cities.Shaqra')}}</option>
<option value="{{ __('cities.Zulfi')}}">{{ __('cities.Zulfi')}}</option>
<option value="{{ __('cities.Arar')}}">{{ __('cities.Arar')}}</option>
<option value="{{ __('cities.Jadidah Arar')}}">{{ __('cities.Jadidah Arar')}}</option>
<option value="{{ __('cities.Al Aflaj (Layla)')}}">{{ __('cities.Al Aflaj (Layla)')}}</option>
<option value="{{ __('cities.Dhurma')}}">{{ __('cities.Dhurma')}}</option>
<option value="{{ __('cities.Dilam')}}">{{ __('cities.Dilam')}}</option>
<option value="{{ __('cities.Diriyah')}}">{{ __('cities.Diriyah')}}</option>
<option value="{{ __('cities.Hawtat Bani Tamim')}}">{{ __('cities.Hawtat Bani Tamim')}}</option>
<option value="{{ __('cities.Hayer')}}">{{ __('cities.Hayer')}}</option>
<option value="{{ __('cities.Huraymila')}}">{{ __('cities.Huraymila')}}</option>
<option value="{{ __('cities.Kharj')}}">{{ __('cities.Kharj')}}</option>
<option value="{{ __('cities.Quwayiyah')}}">{{ __('cities.Quwayiyah')}}</option>
<option value="{{ __('cities.Rayn')}}">{{ __('cities.Rayn')}}</option>
<option value="{{ __('cities.Riyadh')}}">{{ __('cities.Riyadh')}}</option>
<option value="{{ __('cities.Riyadh Airport')}}">{{ __('cities.Riyadh Airport')}}</option>
<option value="{{ __('cities.Rumah')}}">{{ __('cities.Rumah')}}</option>
<option value="{{ __('cities.Ruwaidah')}}">{{ __('cities.Ruwaidah')}}</option>
<option value="{{ __('cities.Dhalim')}}">{{ __('cities.Dhalim')}}</option>
<option value="{{ __('cities.Khurmah')}}">{{ __('cities.Khurmah')}}</option>
<option value="{{ __('cities.Muwayh')}}">{{ __('cities.Muwayh')}}</option>
<option value="{{ __('cities.Ranyah')}}">{{ __('cities.Ranyah')}}</option>
<option value="{{ __('cities.Sayl Al Kabir')}}">{{ __('cities.Sayl Al Kabir')}}</option>
<option value="{{ __('cities.Taif')}}">{{ __('cities.Taif')}}</option>
<option value="{{ __('cities.Turbah')}}">{{ __('cities.Turbah')}}</option>
<option value="{{ __('cities.Bad')}}">{{ __('cities.Bad')}}</option>
<option value="{{ __('cities.Halit Ammar')}}">{{ __('cities.Halit Ammar')}}</option>
<option value="{{ __('cities.Haql')}}">{{ __('cities.Haql')}}</option>
<option value="{{ __('cities.Taima')}}">{{ __('cities.Taima')}}</option>
<option value="{{ __('cities.Tabuk')}}">{{ __('cities.Tabuk')}}</option>
<option value="{{ __('cities.Haql')}}">{{ __('cities.Haql')}}</option>
<option value="{{ __('cities.Qurayyat')}}">{{ __('cities.Qurayyat')}}</option>
<option value="{{ __('cities.Tabarjal')}}">{{ __('cities.Tabarjal')}}</option>
<option value="{{ __('cities.Turayf')}}">{{ __('cities.Turayf')}}</option>
<option value="{{ __('cities.Khamasin')}}">{{ __('cities.Khamasin')}}</option>
<option value="{{ __('cities.Sulayyil')}}">{{ __('cities.Sulayyil')}}</option>
<option value="{{ __('cities.Badar Hunain')}}">{{ __('cities.Badar Hunain')}}</option>
<option value="{{ __('cities.Ummlujj')}}">{{ __('cities.Ummlujj')}}</option>
<option value="{{ __('cities.Wajh')}}">{{ __('cities.Wajh')}}</option>
<option value="{{ __('cities.Yanbu')}}">{{ __('cities.Yanbu')}}</option>
